# @package _global_
defaults:
  - __init__
  - /runner@corprep-gpt4-train_year: corprep-gpt4-train_year
  - override /project: corprep

workflow_name: corprep
verbose: true
tasks:
  - corprep-gpt4-train_year

variables:
  filter_year: 2023
