defaults:
  - corprep-gpt3

_config_name_: corprep-gpt3-${.name}
name: sample
input_filename: ${.name}.parquet
top_n: 10
data_load:
  path: parquet
  data_files: ${get_original_cwd:}/workspace/datasets/filtered/kakao_for_absa/${..input_filename}
  split: train

data_save:
  dataset_path: ${get_original_cwd:}/workspace/datasets/absa_results/${.._config_name_}

agent:
  output_dir: ${get_original_cwd:}/workspace/outputs/predictions/${.._config_name_}
  verbose: true
verbose: true
