defaults:
  - datasets

use_task_as_initial_object: true
steps:
  - uses: load_dataset
    with:
      data_dir: datasets/processed/kakao_filtered
      path: parquet
      split: train
    verbose: true
  # - uses: load_dataset_from_disk
  #   with:
  #     dataset_path: datasets/processed/kakao_filtered
  #     verbose: true
  - uses: sample_dataset
    with:
      sample_size: 1000
      randomize: true
      verbose: true
  - uses: tokenize_dataset
    with:
      tokenizer: mecab
      # batch_size: 3
      num_workers: 30
      text_col: cleaned_text
      token_col: tokenizedText
      remove_columns: [bodyText, analyse_text]
      load_from_cache_file: false
      verbose: true
  - uses: extract_tokens
    with:
      tokenizer: kakao
      # batch_size: 3
      num_workers: 30
      token_col: tokenizedText
      extracted_col: nouns
      nouns_only: true
      remove_columns: [tokenizedText]
      load_from_cache_file: false
      verbose: true
  - uses: save_dataset_to_disk
    with:
      dataset_path: datasets/processed/kakao_nouns
      verbose: true
    verbose: true
