defaults:
  - datasets

use_task_as_initial_object: true
steps:
  - uses: load_dataframes
    with:
      data_files: datasets/filtered/kakao_deduped/train.parquet
      split: train
      verbose: true
  - uses: dataframe_drop_columns
    with:
      columns: [
          "siteName",
          "boardSection",
          "cpName",
          "nouns",
          "createdDt_int",
          "lastModifiedDt",
          "include_ceo",
          "category",
          "serviceUrl",
          "title",
          "writers",
          "cluster",
          "duplicate",
          "fig_filename",
          # "createdDt",
        ]
      verbose: true
    verbose: true
  - uses: dataframe_print_head_and_tail
    verbose: true
  - uses: filter_and_sample_data
    with:
      queries:
        - "createdDt.dt.year == ${variables.filter_year}"
      output_dir: datasets/filtered/kakao_for_absa
      train_filename: train_${variables.filter_year}.parquet
      verbose: true
