defaults:
  - datasets

use_task_as_initial_object: true
steps:
  - uses: load_dataframes
    with:
      data_files: datasets/processed/kakao_nouns_similar_6.parquet
      split: train
      verbose: true
  - uses: dataframe_print_head_and_tail
    verbose: true
  - uses: filter_and_sample_data
    with:
      queries:
        - "duplicate == False"
        - "cleaned_text.str.split().str.len() > 15"
      sample_size: 100
      sample_seed: 123
      output_dir: datasets/filtered/kakao_deduped
      sample_filename: sample.parquet
      train_filename: train.parquet
      discard_filename: discard.parquet
      verbose: true
