defaults:
  - datasets
  - /pipe@pipe_sample: dataset_sample

use_task_as_initial_object: true
steps:
  - uses: pipe_load
    with:
      dataset_path: datasets/processed/kakao
      verbose: true
  - uses: pipe_sample
    with:
      num_samples: 100
      randomize: false
      verbose: true
