defaults:
  - __init__
  - /pipe@load_dataset: load_dataset
  - /pipe@load_dataset_from_disk: load_dataset_from_disk
  - /pipe@save_dataset_to_disk: save_dataset_to_disk
  - /pipe@tokenize_dataset: tokenize_dataset
  - /pipe@sample_dataset: sample_dataset
  - /pipe@extract_tokens: extract_tokens
  - /pipe@dataset_to_pandas: dataset_to_pandas
  - /pipe@dataframe_print_head_and_tail: dataframe_print_head_and_tail
  - /pipe@save_dataframes: save_dataframes
  - /pipe@find_similar_docs_by_clustering: find_similar_docs_by_clustering
  - /pipe@filter_and_sample_data: filter_and_sample_data
  - /pipe@load_dataframes: load_dataframes
  - /pipe@dataset_remove_columns: dataset_remove_columns
  - /pipe@dataframe_drop_columns: dataframe_drop_columns
  - /pipe@dataframe_select_columns: dataframe_select_columns

use_task_as_initial_object: true
steps:
