defaults:
  - datasets

use_task_as_initial_object: true
steps:
  - uses: load_dataset_from_disk
    with:
      dataset_path: datasets/processed/kakao_nouns
      verbose: true
  # - uses: sample_dataset
  #   with:
  #     sample_size: 1000
  #     randomize: true
  #     verbose: true
  - uses: dataset_to_pandas
    verbose: true
  - uses: pandas_print_head
    verbose: true
  - uses: find_similar_docs_by_clustering
    with:
      num_workers: 30
      min_num_docs: 3
      percentile: 90
      distance_threshold: 0.4
      linkage: average
      grouping_freq: W
      grouping_name: Week
      timestamp_col: createdDt
      token_col: nouns
      id_col: newsId
      duplicate_col: duplicate
      dist_fig_col: dist_fig
      output_dir: outputs/figures/kakao_similar_6
      show_fig: false
      save_fig: true
      verbose: true
    verbose: true
  - uses: save_dataframes
    with:
      data_file: datasets/processed/kakao_nouns_similar_6.parquet
