defaults:
  - __general_external_funcs__

run: corprep.datasets.tokenize.extract_tokens
run_with:
  tokenizer_config_name: simple
  num_workers: 1
  batched: true
  batch_size: 1000
  token_col: tokenizedText
  nouns_only: false
  postags:
  stop_postags:
  strip_pos: true
  postag_delim:
  postag_length:
  verbose: ${..verbose}
use_pipe_obj: true
return_pipe_obj: false
